on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.x'  # Specify the desired .NET SDK version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and run NUnit tests
        run: dotnet test --filter TestCategory=YourTestCategory  # Adjust the filter as needed
